apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-deployment # name of the deployment

spec:
  template: # pod defintion
    metadata:
      name: cicdpod # name of the pod
      labels:
        app: cicdpod
        tier: frontend
    spec:
      containers:
        - name: flask-hello-world-container
          image: madhav6798/cicd:flask-hello-world
  replicas: 3
  selector: # Mandatory, Select the pods which needs to be in the replicaset
    matchLabels:
      app: cicdpod
      tier: frontend
