apiVersion: v1
kind: Service
metadata:
  name: cicd-service-nodeport # name of the service

spec:
  type: NodePort # Used for accessing a port externally
  ports:
    - port: 5001 # Service port
      targetPort: 5001 # Pod port, default: same as port
      nodePort: 30009 # Node port which can be used externally, default: auto-assign any free port
  selector: # Which pods to expose externally ?
    app: cicdpod
    tier: frontend
